name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - production
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AXE_TASK }}'
          channelId: live
          projectId: axe-task

      - name: Notification
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always()

