name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - production
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AXE_TASK }}'
          channelId: live
          projectId: axe-task


